project:
  type: website
  pre-render: make index.qmd
  output-dir: docs

title: "Stata's `margins` command"
author: "Josh Errickson"
date: last-modified

format:
  revealjs:
    theme: [default, custom.scss]
    transition: none
    echo: true
    slide_level: 2
    smaller: true
    reveal_options:
      slideNumber: true
      fig_caption: false
      fig_align: "center"
